module.exports = () => {
    return {
        keys : 'MEASURE_ID',
        fields : 'MEASURE_ID, MEASURE_DATE, MEASURE_TIME, MEASURE_EXERCISE_TYPE, MEASURE_EXERCISE_TYPE_TEXT, MEASURE_EXERCISE_TIME, MEASURE_CALORIES_BURNED'        
    }
}